### ISSUE TITLE
Struct CGSize has no member named 'width'

### ISSUE THREAD

**Issue by tarobun** [fjolnir/TLC#2] opened 2012-11-09 23:30 UTC
Using the current trunk, I'm getting the following error when attempting to access the "width" property of a CGSize struct:

```
'struct CGSize' has no member named 'width'
```

Adding the following typedef fixes the problem:

```
typedef struct CGSize { CGFloat width; CGFloat height; } CGSize;
```

**Comment by fjolnir** [comment] 2012-11-10 01:55
Are you using bridge support?
If not you must either manually typedef, or access by index (size.width ==
size[0])

Best regards,
– Fjölnir

On 2012/11/10, at 8:30, tarobun notifications@github.com wrote:

Using the current trunk, I'm getting the following error when attempting to
access the "width" property of a CGSize struct:

'struct CGSize' has no member named 'width'

Adding the following typedef fixes the problem:

typedef struct CGSize { CGFloat width; CGFloat height; } CGSize;

 —
Reply to this email directly or view it on
GitHubhttps://github.com/fjolnir/TLC/issues/2.

**Comment by tarobun** [comment] 2012-11-10 14:30
I am using bridge support, but cannot find right framework to load to get the CGSize definition.
I've tried ApplicationServices, AppKit, Carbon, Quartz, QuartzCore, Foundation, CoreGraphics.

**Comment by fjolnir** [comment] 2012-11-10 16:41
That's weird, but if everything else is working ok, then there's nothing wrong with just manually defining CGSize with ffi, that's what bridgesupport  would do anyway.

I tend to not use bridgesupport myself when using tlc, since it introduces a little delay on startup when it goes through the mountains of xml.

It is convenient to have during development though

**Comment by tarobun** [comment] 2012-11-11 00:31
I've found the CGSize definition in CoreGraphics.bridgesupport and it's defined as:

``` xml
<struct type='{CGSize=&quot;width&quot;f&quot;height&quot;f}' type64='{CGSize=&quot;width&quot;d&quot;height&quot;d}' name='CGSize'/>
```

I think it's not being parsed/typedef correctly...

**Comment by fjolnir** [comment] 2012-11-11 15:52
hm.
I just tested it and this works fine for me:

```
bs.loadFramework("Foundation")
s = bs.NSSizeToCGSize({1,2})
print(s)
print(s.width, s.height)
```

prints

```
cdata<struct CGSize>: 0x079e49e0
1   2
```

**Comment by tarobun** [comment] 2012-11-11 21:07
hmmm... maybe our versions are different, I got the following error:

```
lazy loading fun
luajit: /usr/local/share/lua/5.1/objc/BridgeSupport.lua:124: attempt to index upvalue '_curObj' (a nil value)
stack traceback:
    /usr/local/share/lua/5.1/objc/BridgeSupport.lua:124: in function 'NSSizeToCGSize'
    test.lua:3: in main chunk
    [C]: at 0x0100001710
```

I'm using luajit 2.0.0rc1 and luaexpat-1.2.0

**Comment by tarobun** [comment] 2012-11-12 11:42
Ok... this seems to have fixed it for me, but not the original problem:

from line 122 of BridgeSupport.lua

```
local funcName = _curObj.name
bs[funcName] = function(...)
    print("lazy loading fun.. "..funcName)
    bs[funcName] = ffi.cdef(signature)
    if _loadingGlobally == true then
        _G[funcName] = C[funcName]
    end
    return bs[funcName](...)
end
if _loadingGlobally == true then
    _G[funcName] = bs[funcName]
end
```

**Comment by tarobun** [comment] 2012-11-12 12:09
This breaks for me:

```
local bs = require("objc.BridgeSupport")

bs.loadFramework("AppKit")
bs.loadFramework("Foundation")

s = bs.NSSizeToCGSize({1,2})
print(s)
print(s.width, s.height)
```

If I load Foundation before AppKit, it works.

**Comment by SimonRen** [comment] 2013-01-08 14:03
Would somebody give me a copy of CoreGraphics BridgeSupport file? Or  a way to generate that.

I use iOS-BridgeSupport to parse my iphoneOS5.0.sdk, but some framework failed, including CoreGraphics framework.

I have spend 2 hours on this and cannot figure out a way.

thanks.

**Comment by fjolnir** [comment] 2013-01-08 14:08
> If I load Foundation before AppKit, it works.

 That makes sense, appkit is built on foundation, just load foundation first :) (sorry for the insanely late reply)

> Would somebody give me a copy of CoreGraphics BridgeSupport file? Or a way to generate that.

I think `gen_bridge_metadata` should handle iOS frameworks fine.

**Comment by SimonRen** [comment] 2013-01-08 14:24
My script is:

gen_bridge_metadata -f /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/System/Library/Frameworks/CoreGraphics.framework -c "-DTARGET_OS_IPHONE -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk -framework Foundation" --output "here.bs"

but cannot work. compile just stop because of error.

**Comment by fjolnir** [comment] 2013-01-08 17:27
Then I don't know

**Comment by capr** [comment] 2014-03-26 21:41
Is TLC still developed?

**Comment by fjolnir** [comment] 2014-03-27 09:12
It's still maintained, but I haven't been writing any Lua lately.

**Comment by capr** [comment] 2014-03-27 10:44
Cool. Please add tarobun's bug fix from above.

**Comment by fjolnir** [comment] 2014-03-28 02:53
That's not a fix that belongs in TLC, also I haven't been able to reproduce his issue

**Comment by fjolnir** [comment] 2014-03-28 02:54
If you encounter the same issue you can apply his workaround using:

`ffi.cdef[[ typedef struct CGSize { CGFloat width; CGFloat height; } CGSize; ]]`

**Comment by capr** [comment] 2014-03-28 09:15
Oh, sorry I meant the fix on line 122 on BridgeSupport.lua -- the one that starts with local funcName = _curObj.name -- you shouldn't use _curObj.name inside the closure there because later, when the closure will be executed it will use last value of _curObj which is not necessarily the one you want.

Here's my file with the changes (I also added cdef'ing "cftype" entries): https://github.com/luapower/objc/blob/master/objc/BridgeSupport.lua 

(I would have sent you a pull request to make life easier but I also changed lxp dependency to my own expat binding)

**Comment by fjolnir** [comment] 2018-01-04 02:08
Resolved in https://github.com/fjolnir/TLC/pull/4/files

**Closed as completed by fjolnir** 2018-01-04 02:08 UTC
